// Transport layer to switch between Tauri IPC and Web REST/WebSocket
export type UnlistenFn = () => void;

export interface Event<T> {
  id: number;
  event: string;
  windowLabel: string;
  payload: T;
}

type EventCallback = (event: Event<any>) => void;

// Check if running inside Tauri
export const IS_TAURI = typeof window !== 'undefined' && (window as any).__TAURI_INTERNALS__ !== undefined;

// Token storage key
const TOKEN_KEY = 'oneagent_token';

// In-memory token reference
let cachedToken: string | null = null;

if (typeof window !== 'undefined') {
  // Auto-login: URL token (?token=) always takes priority over localStorage.
  // This handles the case where the server restarts with a new JWT secret —
  // the old token in localStorage would fail verification, but the fresh
  // token in the URL (generated by get_webui_info) is always valid.
  const params = new URLSearchParams(window.location.search);
  const urlToken = params.get('token');
  if (urlToken) {
    cachedToken = urlToken;
    localStorage.setItem(TOKEN_KEY, urlToken);
    // Clean the token from the URL bar
    window.history.replaceState({}, '', window.location.pathname);
  } else {
    cachedToken = localStorage.getItem(TOKEN_KEY);
  }
}

export function setToken(token: string | null) {
  cachedToken = token;
  if (typeof window !== 'undefined') {
    if (token) {
      localStorage.setItem(TOKEN_KEY, token);
    } else {
      localStorage.removeItem(TOKEN_KEY);
    }
  }
  // If token changes, re-establish WebSocket connection in web mode
  if (!IS_TAURI) {
    reconnectWebSocket();
  }
}

export function getToken(): string | null {
  return cachedToken;
}

// WebSocket Event Listeners
const eventListeners = new Map<string, Set<EventCallback>>();

let socket: WebSocket | null = null;
let reconnectTimeout: number | null = null;
let isConnecting = false;

// Global hooks for auth changes
const authStateListeners = new Set<(isAuthenticated: boolean) => void>();

export function subscribeAuthState(listener: (isAuthenticated: boolean) => void): () => void {
  authStateListeners.add(listener);
  // Emit initial state
  listener(IS_TAURI || !!getToken());
  return () => {
    authStateListeners.delete(listener);
  };
}

function notifyAuthState(isAuthenticated: boolean) {
  authStateListeners.forEach((listener) => listener(isAuthenticated));
}

function getBackendUrl(): string {
  if (typeof window === 'undefined') return '';
  const { protocol, hostname, port } = window.location;
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    // If running on Vite dev server (usually port 1420 or 5173), point to 19520
    if (port && port !== '19520') {
      return `${protocol}//${hostname}:19520`;
    }
  }
  return `${protocol}//${hostname}${port ? `:${port}` : ''}`;
}

function getWebSocketUrl(): string {
  const backendUrl = getBackendUrl();
  const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  const host = backendUrl.replace(/^https?:\/\//, '');
  return `${wsProtocol}//${host}/ws`;
}

interface TauriCore {
  invoke<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
}

interface TauriEvent {
  listen<T>(
    event: string,
    handler: (event: Event<T>) => void,
    options?: any
  ): Promise<UnlistenFn>;
}

// Dynamic imports for Tauri to avoid crashing in standard browsers
let tauriCoreModule: any = null;
let tauriEventModule: any = null;

async function getTauriCore(): Promise<TauriCore> {
  if (!tauriCoreModule) {
    tauriCoreModule = await import('@tauri-apps/api/core');
  }
  return tauriCoreModule;
}

async function getTauriEvent(): Promise<TauriEvent> {
  if (!tauriEventModule) {
    tauriEventModule = await import('@tauri-apps/api/event');
  }
  return tauriEventModule;
}

export async function invoke<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  if (IS_TAURI) {
    const tauri = await getTauriCore();
    return await tauri.invoke<T>(command, args);
  }

  // REST API request in Web mode
  const backendUrl = getBackendUrl();
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  const token = getToken();
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  // Also pass token as query param as a fallback for network environments
  // where Authorization headers may be stripped by proxies
  const tokenParam = token ? `?token=${encodeURIComponent(token)}` : '';
  const response = await fetch(`${backendUrl}/api/invoke/${command}${tokenParam}`, {
    method: 'POST',
    headers,
    body: JSON.stringify(args || {}),
  });

  if (response.status === 401) {
    notifyAuthState(false);
    throw new Error('Unauthorized');
  }

  if (!response.ok) {
    const errText = await response.text();
    let errJson;
    try {
      errJson = JSON.parse(errText);
    } catch {
      // Ignore
    }
    throw new Error(errJson?.error || errText || `HTTP ${response.status}`);
  }

  return await response.json();
}

export async function login(password: string): Promise<boolean> {
  if (IS_TAURI) return true;

  const backendUrl = getBackendUrl();
  try {
    const response = await fetch(`${backendUrl}/api/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ password }),
    });

    if (!response.ok) {
      return false;
    }

    const data = await response.json();
    if (data.token) {
      setToken(data.token);
      notifyAuthState(true);
      return true;
    }
    return false;
  } catch (err) {
    console.error('Login error:', err);
    return false;
  }
}

export async function logout(): Promise<void> {
  if (IS_TAURI) return;

  const backendUrl = getBackendUrl();
  try {
    await fetch(`${backendUrl}/api/logout`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${getToken()}`,
      },
    });
  } catch (err) {
    console.error('Logout error:', err);
  } finally {
    setToken(null);
    notifyAuthState(false);
  }
}

export async function listen<T>(
  event: string,
  handler: (event: Event<T>) => void,
  options?: any
): Promise<UnlistenFn> {
  if (IS_TAURI) {
    const tauri = await getTauriEvent();
    return await tauri.listen(event, handler, options);
  }

  // Register in local WebSocket listeners
  if (!eventListeners.has(event)) {
    eventListeners.set(event, new Set());
  }
  eventListeners.get(event)!.add(handler);

  // Ensure WebSocket is connected in web mode
  ensureWebSocketConnected();

  // Return unlisten function
  return () => {
    const listeners = eventListeners.get(event);
    if (listeners) {
      listeners.delete(handler);
      if (listeners.size === 0) {
        eventListeners.delete(event);
      }
    }
  };
}

export function ensureWebSocketConnected() {
  if (IS_TAURI || socket || isConnecting) return;

  const token = getToken();
  if (!token) {
    // If not authenticated, notify auth state as false
    notifyAuthState(false);
    return;
  }

  isConnecting = true;
  const wsUrl = `${getWebSocketUrl()}?token=${token}`;

  try {
    const ws = new WebSocket(wsUrl);
    socket = ws;

    ws.onopen = () => {
      isConnecting = false;
      if (reconnectTimeout) {
        clearTimeout(reconnectTimeout);
        reconnectTimeout = null;
      }
      notifyAuthState(true);
    };

    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        const eventName = data.event;
        const payload = data.payload;

        if (eventName && eventListeners.has(eventName)) {
          const listeners = eventListeners.get(eventName)!;
          const ev: Event<any> = {
            id: Date.now(),
            event: eventName,
            windowLabel: 'main',
            payload,
          };
          listeners.forEach((listener) => {
            try {
              listener(ev);
            } catch (err) {
              console.error('Error in event listener:', err);
            }
          });
        }
      } catch (err) {
        console.error('Failed to parse WebSocket message:', err);
      }
    };

    ws.onclose = (event) => {
      socket = null;
      isConnecting = false;
      
      // If code is policy violation or unauthorized, trigger logout/unauth
      if (event.code === 4001 || event.code === 1008 || (event.reason && event.reason.toLowerCase().includes('unauthorized'))) {
        setToken(null);
        notifyAuthState(false);
        return;
      }

      // Schedule reconnect if still logged in
      if (getToken()) {
        scheduleReconnect();
      }
    };

    ws.onerror = (err) => {
      console.error('WebSocket error:', err);
      ws.close();
    };
  } catch (err) {
    console.error('Failed to instantiate WebSocket:', err);
    isConnecting = false;
    if (getToken()) {
      scheduleReconnect();
    }
  }
}

function scheduleReconnect() {
  if (reconnectTimeout) return;
  reconnectTimeout = window.setTimeout(() => {
    reconnectTimeout = null;
    ensureWebSocketConnected();
  }, 3000);
}

function reconnectWebSocket() {
  if (socket) {
    socket.close();
    socket = null;
  }
  ensureWebSocketConnected();
}
